networks:
  default:
    external: true
    name: ddev_default
services:
  db:
    build:
      args:
        BASE_IMAGE: drud/ddev-dbserver-mariadb-10.2:v1.16.0
        gid: '1001'
        uid: '1000'
        username: fmizzell
      context: /home/fmizzell/Workspace/mock-chain/.ddev/db-build
      dockerfile: /home/fmizzell/Workspace/mock-chain/.ddev/.dbimageBuild/Dockerfile
    command: ''
    container_name: ddev-mock-chain-db
    environment:
      COLUMNS: '92'
      DDEV_HOSTNAME: mock-chain.ddev.site
      DDEV_PHP_VERSION: '7.3'
      DDEV_PRIMARY_URL: https://mock-chain.ddev.site
      DDEV_PROJECT: mock-chain
      DDEV_PROJECT_TYPE: php
      DDEV_ROUTER_HTTPS_PORT: '443'
      DDEV_ROUTER_HTTP_PORT: '80'
      DDEV_SITENAME: mock-chain
      DDEV_TLD: ddev.site
      DOCKER_IP: 127.0.0.1
      HOST_DOCKER_INTERNAL_IP: 172.17.0.1
      IS_DDEV_PROJECT: "true"
      LINES: '68'
      TZ: ''
    healthcheck:
      interval: 1s
      retries: 120
      start_period: 2m
      timeout: 2m
    hostname: mock-chain-db
    image: drud/ddev-dbserver-mariadb-10.2:v1.16.0-mock-chain-built
    labels:
      com.ddev.app-type: php
      com.ddev.approot: /home/fmizzell/Workspace/mock-chain
      com.ddev.platform: ddev
      com.ddev.site-name: mock-chain
    ports:
    - 127.0.0.1::3306/tcp
    restart: "no"
    stop_grace_period: 60s
    user: 1000:1001
    volumes:
    - ddev-global-cache:/mnt/ddev-global-cache:rw
    - source: /home/fmizzell/Workspace/mock-chain/.ddev
      target: /mnt/ddev_config
      type: bind
    - source: mariadb-database
      target: /var/lib/mysql
      type: volume
      volume:
        nocopy: true
  dba:
    container_name: ddev-mock-chain-dba
    environment:
      HTTPS_EXPOSE: 8037:8036
      HTTP_EXPOSE: 8036:8036
      PMA_PASSWORD: root
      PMA_USER: root
      TZ: ''
      UPLOAD_LIMIT: 1024M
      VIRTUAL_HOST: mock-chain.ddev.site
    healthcheck:
      interval: 2m
      retries: 1
      timeout: 2s
    hostname: mock-chain-dba
    image: phpmyadmin:5
    labels:
      com.ddev.app-type: php
      com.ddev.approot: /home/fmizzell/Workspace/mock-chain
      com.ddev.platform: ddev
      com.ddev.site-name: mock-chain
    links:
    - db
    ports:
    - target: 80
    restart: "no"
  web:
    build:
      args:
        BASE_IMAGE: drud/ddev-webserver:v1.16.3
        gid: '1001'
        uid: '1000'
        username: fmizzell
      context: /home/fmizzell/Workspace/mock-chain/.ddev/web-build
      dockerfile: /home/fmizzell/Workspace/mock-chain/.ddev/.webimageBuild/Dockerfile
    cap_add:
    - SYS_PTRACE
    container_name: ddev-mock-chain-web
    environment:
      COLUMNS: '92'
      DDEV_DOCROOT: ''
      DDEV_HOSTNAME: mock-chain.ddev.site
      DDEV_PHP_VERSION: '7.3'
      DDEV_PRIMARY_URL: https://mock-chain.ddev.site
      DDEV_PROJECT: mock-chain
      DDEV_PROJECT_TYPE: php
      DDEV_ROUTER_HTTPS_PORT: '443'
      DDEV_ROUTER_HTTP_PORT: '80'
      DDEV_SITENAME: mock-chain
      DDEV_TLD: ddev.site
      DDEV_WEBSERVER_TYPE: nginx-fpm
      DDEV_XDEBUG_ENABLED: "false"
      DEPLOY_NAME: local
      DOCKER_IP: 127.0.0.1
      DOCROOT: ''
      DRUSH_ALLOW_XDEBUG: '1'
      DRUSH_OPTIONS_URI: https://mock-chain.ddev.site
      HOST_DOCKER_INTERNAL_IP: 172.17.0.1
      HTTPS_EXPOSE: 443:80,8026:8025
      HTTP_EXPOSE: 80:80,8025:8025
      IS_DDEV_PROJECT: "true"
      LINES: '68'
      SSH_AUTH_SOCK: /home/.ssh-agent/socket
      TZ: ''
      VIRTUAL_HOST: mock-chain.ddev.site
      XDEBUG_MODE: coverage
    external_links:
    - ddev-router:mock-chain.ddev.site
    extra_hosts:
      host.docker.internal: 172.17.0.1
    healthcheck:
      interval: 1s
      retries: 120
      start_period: 2m
      timeout: 2m
    hostname: mock-chain-web
    image: drud/ddev-webserver:v1.16.3-mock-chain-built
    labels:
      com.ddev.app-type: php
      com.ddev.approot: /home/fmizzell/Workspace/mock-chain
      com.ddev.platform: ddev
      com.ddev.site-name: mock-chain
    links:
    - db
    ports:
    - 127.0.0.1::80/tcp
    - 127.0.0.1::443/tcp
    restart: "no"
    user: 1000:1001
    volumes:
    - /home/fmizzell/Workspace/mock-chain/.ddev/apache:/etc/apache2/sites-enabled:ro
    - /home/fmizzell/Workspace/mock-chain/.ddev/nginx_full:/etc/nginx/sites-enabled:ro
    - ddev-ssh-agent_socket_dir:/home/.ssh-agent:rw
    - ddev-global-cache:/mnt/ddev-global-cache:rw
    - /home/fmizzell/Workspace/mock-chain/.ddev:/mnt/ddev_config:ro
    - consistency: cached
      source: /home/fmizzell/Workspace/mock-chain
      target: /var/www/html
      type: bind
version: '3.6'
volumes:
  ddev-global-cache:
    name: ddev-global-cache
  ddev-ssh-agent_socket_dir:
    external: true
    name: ddev-ssh-agent_socket_dir
  mariadb-database:
    name: mock-chain-mariadb

